config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :locations  do
	  resources :events, only: [:new, :create, :edit, :update]
  	resources :flats, only: [:show, :new, :create, :edit, :update]
  end
  resources :events, only: [:destroy]
  resources :tenants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :tenants, through: :event_bookings
  has_many :event_bookings, dependent: :destroy

  validates :name, presence: true
  validates :date, presence: true
  validates :capacity, presence: true
  validates :address, presence: true
end

app/models/event_booking.rb
class EventBooking < ApplicationRecord
  belongs_to :event
  belongs_to :tenant
  validates :expired, inclusion: { in: [true, false] }
  validates :approved, inclusion: { in: [true, false] }
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :location
  has_many :flat_contracts, dependent: :destroy
  has_many :tenants, through: :flat_contracts
  validates :flat_type, presence: true
  validates :availability, inclusion: { in: [true, false] }
  validates :address, presence: true
  validates :occupancy, presence: true
  validates :bedrooms, presence: true
  validates :bathrooms, presence: true
  validates :flat_number, presence: true

  def available?
    availability = tenants.count < occupancy
  end
end

app/models/flat_contract.rb
class FlatContract < ApplicationRecord
  belongs_to :tenant
  belongs_to :flat
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :flats
  has_many :events
  validates :name, presence: true
  validates :open, inclusion: { in: [true, false] }
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_many :flat_contracts
  has_many :flats, through: :flat_contracts
  has_many :event_bookings
  has_many :events, through: :event_bookings
  validates :first_name, presence: true
  validates :last_name, presence: true
  #  format for email validation
  validates :email, presence: true, format: {
    with: URI::MailTo::EMAIL_REGEXP,
    message: 'Only valid emails allowed'
  }
  validates :birthday, presence: true
  validates :username, presence: true

  def formated_number
    formatted_phone_number(phone_number)
  end
  # formated_number = formatted_phone_number(phone_number)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flat_contracts, dependent: :destroy
  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_location, only: %i[new create]

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    authorize @event
    @event.location = @location
    @event.user = current_user
    if @event.save
      flash[:notice] = "Your event has been set!"
      redirect_to location_path(@location)
    else
      redirect_to new_location_event_path(@location)
    end
end

  def edit; end

  def update; end

  def destroy
    @event = Event.find(params[:id])
    authorize @event
    @location = @event.location
    @event.destroy
    flash[:alert] = "Your event has been cancelled"
    redirect_to location_path(@location)
  end

  private

  def set_location
    @location = Location.find(params[:location_id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :date, :capacity, :address)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show]
  before_action :set_location, only: %i[new create]

  def show
    @flat.available?
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    authorize @flat
    @flat.location = @location
    if @flat.save
      flash[:notice] = "Your flat has been set!"
      redirect_to location_flat_path(@location, @flat)
    else
      redirect_to new_location_flat_path(@location)
    end
  end

  def destroy; end

  private

  def flat_params
    params.require(:flat).permit(:flat_type, :address, :occupancy, :bedrooms, :bathrooms, :floor_number, :availability)
  end

  def set_flat
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def set_location
    @location = Location.find(params[:location_id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show]
  def index
    @locations = policy_scope(Location)
  end

  def show; end

  def new
    @location = Location.new
    authorize @location
  end

  def create
    @location = Location.new(location_params)
    authorize @location
    if @location.save
      flash[:notice] = "Your location has been created"
      redirect_to location_path(@location)
    else
      redirect_to new_location_path(@location)
    end
  end

  private

  def set_location
    @location = Location.find(params[:id])
    authorize @location
  end

  def location_params
    params.require(:location).permit(:city, :name, :open)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[show edit update]
  def index
    @tenants = policy_scope(Tenant)
  end

  def show
    authorize @tenant
  end

  def new
    @tenant = Tenant.new
    authorize @tenant
  end

  def create
    @tenant = Tenant.new(tenant_params)
    authorize @tenant
    if @tenant.save
      flash[:notice] = "Your Tenant has been created"
      redirect_to tenants_path
    else
      flash[:alert] = "Invalid Inputs"
      redirect_to new_tenant_path
    end
  end

  private

  def set_tenant
    @tenant = Tenant.find(params[:id])
  end

  def tenant_params
    params.require(:tenant).permit(:first_name, :last_name, :email, :birthday, :username, :phone_number)
  end
end

app/helpers/tenants_helper.rb
module TenantsHelper
  include ActionView::Helpers::NumberHelper

  def format_phone(phone_number)
    number_to_phone(phone_number, delimiter: "-")
  end
end

app/views/events/_form.html.erb
<div class="container" style="width: 400px">
	<%= simple_form_for [@location, @flat] do |f| %>
	  <% @types = %w(Studio 2-Bedroom 1-Bedroom 3-Bedroom) %>
	  <%=f.input :name %>
	  <%=f.input :description, as: :text	 %>
	  <%=f.input :address, as: :integer %>
	  <%=f.input :date, as: :datetime %>
	  <%=f.input :capacity, as: :integer %>
	  <%= f.button :submit, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second"%>
	<%  end %> 
</div>

app/views/events/new.html.erb
<div class="container" style="width: 400px">
	<%= simple_form_for [@location, @event], remote: true do |f| %>
	  <%=f.input :name %>
	  <%=f.input :description	%>
	  <%=f.input :address  %>
	  <%=f.input :date, as: :datetime %>
	  <%=f.input :capacity, as: :integer %>
	  <%= f.button :submit, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second"%>
	<%  end %> 
</div>

app/views/flats/new.html.erb
<div class="container" style="width: 400px">
	<%= simple_form_for [@location, @flat] do |f| %>
	  <% @types = %w(Studio 2-Bedroom 1-Bedroom 3-Bedroom) %>
	  <%=f.input :flat_type, collection: @types  %>
	  <%=f.input :address  %>
	  <%=f.input :occupancy, as: :integer %>
	  <%=f.input :bedrooms, as: :integer%>
	  <%=f.input :bathrooms, as: :integer %>
	  <%=f.input :floor_number, as: :integer%>
	  <%=f.input :availability, as: :boolean%>
	  <%= f.button :submit, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second" %>
	<%  end %> 
</div>

app/views/flats/show.html.erb
<% if @flat.flat_type == "Studio" %>
	<% image = "studio.jpg"%>
<% elsif @flat.flat_type == "2-Bedroom"%>
	<% image = "2bedroom.jpg"%>
<% elsif @flat.flat_type == "3-Bedroom"%>
	<% image = "bed_room.jpg"%>
<% else %>
	<% image = "kitchen.jpg" %>
<% end %>
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path image %>);">
	<div class="banner-content">
		<h1><%= @flat.flat_type %></h1>
		<p><%= @flat.location.name %> - <%= @flat.location.city %></p>
		<%= button_to	"Edit Flat", edit_location_flat_path(@flat), method: :get, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second" %>	  	
	</div>
</div>

<div class="container flat-s-wrapper">
	<div class="row">
		<div class="col-md-8">
			<div class="row">
				<div class="col-md-12 flat-info-wrapper">
					<div class="row">
						<div class="col-xs-4">
							<%  if @flat.available? %>
								Vacancy <span><i class="fas fa-calendar-check"></i></span>
							<% else %>
								Full <span><i class="fas fa-calendar-times"></i></span>
							<% end %>
						</div>
						<div class="col-xs-4">
							<%= @flat.bedrooms <= 1 ? "#{@flat.bedrooms} room" : "#{@flat.bedrooms} rooms"  %> 
						</div>
						<div class="col-xs-4">
							<%= @flat.bathrooms <= 1 ? "#{@flat.bathrooms} bath" : "#{@flat.bathrooms} baths" %>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-4">
							# <%= @flat.flat_number %>
						</div>
						<div class="col-xs-4 ">
							<%= @flat.floor_number %>
						</div>
						<div class="col-xs-12">
							<%= @flat.address %>
						</div>
					</div>
				</div>
			</div>
			<div class="row flat-row-tenant-wrapper">
				<div class="col-md-12 flat-tenant-wrapper">
					<div class="row">
						
					<% @flat.tenants.each do |tenant| %>

					<div class="col-xs-12 col-sm-6 col-lg-4">
						<div class="skill-card">
							<header class="skill-card__header">
					
								<img class="skill-card__icon" src=<%= image_path "steve.jpg" %>/>
							</header>
							<section class="skill-card__body">
								<h3 class="skill-card__title"><%= "#{tenant.first_name} #{tenant.last_name}" %></h3>
								<span class="skill-card__duration">
									<div><%= "Start: #{tenant.flat_contracts.first.start_date}" %></div>
									<div><%= "End: #{tenant.flat_contracts.first.end_date}"%></div>
								</span>
								<ul class="skill-card__knowledge">
									<li><i class="fas fa-user-tag fa"></i>   <%= tenant.username %></li>
									<li><a href="mailto:<%= tenant.email %>" class="envol"><i class="fas fa-envelope fa"></i>   <%= tenant.email %></a></li>
									<li><i class="fas fa-mobile fa"></i>   <%= tenant.phone %></li>
									<li><i class="fas fa-birthday-cake"></i>   <%= tenant.birthday %></li>
								</ul>
								</section>
						</div>
					</div>
					<% end %>
					</div>

				</div>
			</div>
			<!-- <div class="row">
				<div class="col-md-12 flat-event-wrapper">
					<div class="flat-s-events">Events</div>	
				</div>
			</div> -->
		</div>
		<div class="col-md-4">
			<!-- <div class="flat-s-column f-s-c-m">Messages</div>	 -->
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/locations/index.html.erb
<div class="container">
	<h1> Locations </h1>
	<div class="buttons-index">
		<%= button_to	"New Location", new_location_path, method: :get, class: "mdl-button mdl-js-button mdl-button--raised md-btn-primary" %>	
	</div>

	<% @locations.each do |location| %>
	<div class="col-md-4">
			<div class="card location-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.5)), url(<%= image_path 'paris.jpg' %>);">
		  	<div class="card-category">Available!</div>
		  	<div class="card-description">
		   		<h2><%= location.name %></h2>
	    		<h6><%= location.city %></h6>
		  	</div>
	  		<%= link_to "", location_path(location), class: "card-link" %>
			</div>
	</div>
	<% end %>	

</div>

app/views/locations/new.html.erb
<div class="container" style="width: 400px">
	<%= simple_form_for @location do |f| %>
	  <% @types = %w(Studio 2-Bedroom 1-Bedroom 3-Bedroom) %>
	  <%=f.input :city %>
	  <%=f.input :name %>
	  <%=f.input :open, as: :boolean%>
	  <%= f.button :submit, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second" %>
	<%  end %> 
</div>

app/views/locations/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_path "paris.jpg" %>);">
  <div class="banner-content">
    <h1><%= @location.name %></h1>
    <h4><%= @location.city %></h4>
		<%= button_to	"New Flat", new_location_flat_path(@location), method: :get, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second" %>	  	
  </div>
</div>



<div class="loc-s-wrapper container">
	<div class="row">
		<div class="col-md-6 loc-inside-wrapper">
			<div class="row">
				<% @location.flats.each do |flat| %>
					<div class="col-sm-12" id="text-decoration">
						<%= link_to location_flat_path(@location, flat) do %>
							<div class="loc-s-item">
								<div class="flat-tenant-s">
									<% flat.tenants.each do |tenant| %>
										<img src='https://kitt.lewagon.com/placeholder/users/krokrob' class="avatar-bordered"/>
									<% end %>
						
								</div>
								<span class="border"></span>
								<div class="flat-info-s">
									<div class="flat-type-s">
										<div><span class='label label-warning'><%= flat.flat_type %></span></div>
										<div>Floor: <strong><%= flat.floor_number %></strong></div>
									</div>
									<div class="flat-add-s"><%= flat.address %></div>
								</div>
								<span class="border"></span>
								<div class="flat-avail-s">
									<div class="flat-room-s">
										<div>Bed: <strong><%= flat.bedrooms %></strong></div>
										<div>Bath: <strong><%= flat.bathrooms %></strong></div>
									</div>
									<div class="flat-avail-cell-s">Avail: 
										<% if flat.available?  %>
											<span class="label label-warning">Yes</span>
										<% else %>
											<span class="label label-danger">no</span>
										<% end %>
									</div>
								</div>
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
		<div class="col-md-6 loc-inside-wrapper">
			<div class="row">
				<div class="col-md-12">
				<%= button_to	"New Event", new_location_event_path(@location), method: :get, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second" %>

				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<div class="row events-wrapper">
						<% @location.events.each do |event| %>
						<div class=" col-md-6 col-sm-4 col-xs-12">
							<div class="card-loc-s">
						<%=link_to event_path(event), method: :delete, data: {confirm: "Are you sure?"} do %> 
          		<i class="fas fa-trash-alt delete-event fa"></i>
        			<% end %>
								<div class="row">
									<div class="col-xs-6">
										<span><i class="fas fa-calendar-alt"></i></span><div class="event-day"><%= event.date.day %></div>
									</div>
									<div class="col-xs-6">
										<div class="row">
											<div class="col-xs-12 event-month">
												<%= event.date.strftime('%b') %>
											</div>
										</div>
										<div class="row">
											<div class="col-xs-12 event-hour">
												<%= event.date.strftime('%H:%M') %>
											</div>
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-xs-12">
										<div class="row">
											<div class="col-xs-12 event-name">
												<%= event.name %>
											</div>
											<div class="col-xs-12 event-des">
												<%= event.description %>
											</div>
										</div>
									</div>
								</div>
								<div class="row attendees-wrap">
										<%event.event_bookings.each do |eb| %>
									<div class="col-xs-3 ">
										<img  class="avatar-bordered" src="https://randomuser.me/api/portraits/women/16.jpg" alt="Guests" />
									</div>
									<% end %>
								</div>
							</div>
						</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
		

app/views/pages/home.html.erb
<div class="container">
	<div class=" card-buttons-container">
		<%= link_to tenants_path do  %>
			<div class="home-card col-md-6">
				<div class="home-icon home-tenant"></div>
				<div class="home-card-name">Tenants</div>
			</div>
		<%end %>
		<%= link_to locations_path do  %>
			<div class="home-card col-md-6">
				<div class="home-icon home-location"></div>
				<div class="home-card-name">Location</div>
			</div>
		<%end%>
	</div>
</div>

app/views/shared/_avatar.html.erb
<img src='https://kitt.lewagon.com/placeholder/users/krokrob' class="avatar-bordered"/>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "colonies.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Home", "/", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Flats", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="avatar-email dropdown-toggle" id="navbar-wagon-menu", data-toggle="dropdown"><%= current_user.email %></div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Messages</a></li>
        <li><a href="#">Flats</a></li>
        <li><a href="#">Tenants</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_responsive_card.html.erb
<div class="skill-card">
  <header class="skill-card__header">
  	<img class="skill-card__icon" src="https://upload.wikimedia.org/wikipedia/commons/3/38/HTML5_Badge.svg" alt="HTML5 Logo"/>
  </header>
  <section class="skill-card__body">
    <h2 class="skill-card__title">html</h2><span class="skill-card__duration">6 ans d'expérience</span>
    <ul class="skill-card__knowledge">
      <li>HTML5</li>
      <li>Sémantique</li>
      <li>SVG</li>
      <li>Canvas</li>
    </ul>
  </section>
</div>

app/views/tenants/edit.html.erb
<div class="container" style="width: 400px">
	<%= simple_form_for @tenant do |f| %>
	  <%=f.input :first_name %>
	  <%=f.input :last_name %>
	  <%=f.input :email, as: :email%>
	  <%=f.input format_phone(:phone), label: "Phone: XXX-XXX-XXXX"%>
	  <%=f.input :username%>
	  <%=f.input :birthday, as: :date%>
	  <%= f.button :submit, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second" %>
	<%  end %> 
</div>

app/views/tenants/index.html.erb
<h1 class="tenant-index-header">Tenants</h1>

<div class="container tenant-index-wrapper">
	<div class="row">
		<div class="col-md-12">
			<div class="buttons-index">
				<%= button_to	"Add Tenant", new_tenant_path, method: :get, class: "mdl-button mdl-js-button mdl-button--raised md-btn-primary" %>	
			</div>	
		</div>
	</div>
	<div class="row tenant-list">
		<% @tenants.each do |tenant| %>
		<div class="col-xs-12 tenant-wrapper">
			<div class="row">
				<div class="col-xs-1 t-av">
					<img  src='https://kitt.lewagon.com/placeholder/users/krokrob' class="avatar-bordered mdl-list_item-avatar"/>
				</div>
				<div class="col-xs-3 t-name">
					<div class="col-xs-12 tenant-name"><%= tenant.last_name %>, <%= tenant.first_name %></div>
				</div>
				<div class="col-xs-8">
					<div class="row">
						<div class="col-xs-6 t-email"><%= tenant.email %></div>
						<div class="col-xs-4 t-l-name"><%= tenant.flats.first.location.name %></div>
					</div>
					<div class="row">
						<div class="col-xs-6 t-phone"><%= tenant.phone%></div>
						<div class="col-xs-4 t-flat-num"># <%= tenant.flats.first.flat_number%></div>
					</div>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

			

app/views/tenants/new.html.erb
<div class="container" style="width: 400px">
	<%= simple_form_for @tenant do |f| %>
	  <%=f.input :first_name %>
	  <%=f.input :last_name %>
	  <%=f.input :email, as: :email%>
	  <%=f.input format_phone(:phone), label: "Phone: XXX-XXX-XXXX"%>
	  <%=f.input :username%>
	  <%=f.input :birthday, as: :date%>
	  <%= f.button :submit, class: "mdl-button mdl-js-button mdl-button--raised", id: "md-second" %>
	<%  end %> 
</div>

app/views/tenants/show.html.erb
<h1>TENANT SHOW PAGE</h1>

<p><%= link_to 'home', '/' %></p>